name: "Create VMs"
  openstack.cloud.server:
    cloud: "{{ cloud }}"
    state: present
    name: "{{ vm_name_prefix }}-{{ item }}"
    flavor: "{{ flavor }}"
    image: "{{ image }}"
    key_name: "{{ key_name }}"
    network: "{{ network_name }}"
    wait: yes
    auto_ip: false
  register: created_vm
  loop: "{{ range(1, 5) | list }}"  # Loop to create 4 VMs